In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import torch
import torch.nn as nn

In [ ]:
!pip install fastai

Requirement already satisfied: fastai in /usr/local/lib/python3.11/dist-packages (2.7.18)
Requirement already satisfied: pip in /usr/local/lib/python3.11/dist-packages (from fastai) (24.1.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from fastai) (24.2)
Requirement already satisfied: fastdownload<2,>=0.0.5 in /usr/local/lib/python3.11/dist-packages (from fastai) (0.0.7)
Requirement already satisfied: fastcore<1.8,>=1.5.29 in /usr/local/lib/python3.11/dist-packages (from fastai) (1.7.28)
Requirement already satisfied: torchvision>=0.11 in /usr/local/lib/python3.11/dist-packages (from fastai) (0.20.1+cu121)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from fastai) (3.10.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from fastai) (2.2.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from fastai) (2.32.3)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.11/dist-packages (from fastai) (6.0.2)
Requirement already satisfied: fastprogress>=0.2.4 in /usr/local/lib/python3.11/dist-packages (from fastai) (1.0.3)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.11/dist-packages (from fastai) (11.1.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from fastai) (1.6.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from fastai) (1.13.1)
Requirement already satisfied: spacy<4 in /usr/local/lib/python3.11/dist-packages (from fastai) (3.7.5)
Requirement already satisfied: torch<2.6,>=1.10 in /usr/local/lib/python3.11/dist-packages (from fastai) (2.5.1+cu121)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.11/dist-packages (from spacy<4->fastai) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from spacy<4->fastai) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.11/dist-packages (from spacy<4->fastai) (1.0.11)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.11/dist-packages (from spacy<4->fastai) (2.0.10)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.11/dist-packages (from spacy<4->fastai) (3.0.9)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in /usr/local/lib/python3.11/dist-packages (from spacy<4->fastai) (8.2.5)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.11/dist-packages (from spacy<4->fastai) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.11/dist-packages (from spacy<4->fastai) (2.5.0)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.11/dist-packages (from spacy<4->fastai) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.11/dist-packages (from spacy<4->fastai) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from spacy<4->fastai) (0.15.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.11/dist-packages (from spacy<4->fastai) (4.67.1)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.11/dist-packages (from spacy<4->fastai) (2.10.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from spacy<4->fastai) (3.1.5)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from spacy<4->fastai) (75.1.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.11/dist-packages (from spacy<4->fastai) (3.5.0)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.11/dist-packages (from spacy<4->fastai) (1.26.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->fastai) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->fastai) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->fastai) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->fastai) (2024.12.14)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch<2.6,>=1.10->fastai) (3.16.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.11/dist-packages (from torch<2.6,>=1.10->fastai) (4.12.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch<2.6,>=1.10->fastai) (3.4.2)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch<2.6,>=1.10->fastai) (2024.10.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /usr/local/lib/python3.11/dist-packages (from torch<2.6,>=1.10->fastai) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /usr/local/lib/python3.11/dist-packages (from torch<2.6,>=1.10->fastai) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /usr/local/lib/python3.11/dist-packages (from torch<2.6,>=1.10->fastai) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch<2.6,>=1.10->fastai) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /usr/local/lib/python3.11/dist-packages (from torch<2.6,>=1.10->fastai) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /usr/local/lib/python3.11/dist-packages (from torch<2.6,>=1.10->fastai) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /usr/local/lib/python3.11/dist-packages (from torch<2.6,>=1.10->fastai) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /usr/local/lib/python3.11/dist-packages (from torch<2.6,>=1.10->fastai) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /usr/local/lib/python3.11/dist-packages (from torch<2.6,>=1.10->fastai) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch<2.6,>=1.10->fastai) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /usr/local/lib/python3.11/dist-packages (from torch<2.6,>=1.10->fastai) (12.1.105)
Requirement already satisfied: triton==3.1.0 in /usr/local/lib/python3.11/dist-packages (from torch<2.6,>=1.10->fastai) (3.1.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch<2.6,>=1.10->fastai) (1.13.1)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.11/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch<2.6,>=1.10->fastai) (12.6.85)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch<2.6,>=1.10->fastai) (1.3.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->fastai) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->fastai) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->fastai) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->fastai) (1.4.8)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->fastai) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib->fastai) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->fastai) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->fastai) (2024.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->fastai) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->fastai) (3.5.0)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.11/dist-packages (from langcodes<4.0.0,>=3.2.0->spacy<4->fastai) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<4->fastai) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<4->fastai) (2.27.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib->fastai) (1.17.0)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.11/dist-packages (from thinc<8.3.0,>=8.2.2->spacy<4->fastai) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.11/dist-packages (from thinc<8.3.0,>=8.2.2->spacy<4->fastai) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy<4->fastai) (8.1.8)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy<4->fastai) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy<4->fastai) (13.9.4)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<4->fastai) (0.20.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.11/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<4->fastai) (7.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->spacy<4->fastai) (3.0.2)
Requirement already satisfied: marisa-trie>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy<4->fastai) (1.2.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<4->fastai) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<4->fastai) (2.18.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy<4->fastai) (1.17.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<4->fastai) (0.1.2)

In [ ]:
!pip install timm

Requirement already satisfied: timm in /usr/local/lib/python3.11/dist-packages (1.0.13)
Requirement already satisfied: torch in /usr/local/lib/python3.11/dist-packages (from timm) (2.5.1+cu121)
Requirement already satisfied: torchvision in /usr/local/lib/python3.11/dist-packages (from timm) (0.20.1+cu121)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.11/dist-packages (from timm) (6.0.2)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.11/dist-packages (from timm) (0.27.1)
Requirement already satisfied: safetensors in /usr/local/lib/python3.11/dist-packages (from timm) (0.5.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface_hub->timm) (3.16.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub->timm) (2024.10.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub->timm) (24.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface_hub->timm) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub->timm) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub->timm) (4.12.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch->timm) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch->timm) (3.1.5)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /usr/local/lib/python3.11/dist-packages (from torch->timm) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /usr/local/lib/python3.11/dist-packages (from torch->timm) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /usr/local/lib/python3.11/dist-packages (from torch->timm) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch->timm) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /usr/local/lib/python3.11/dist-packages (from torch->timm) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /usr/local/lib/python3.11/dist-packages (from torch->timm) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /usr/local/lib/python3.11/dist-packages (from torch->timm) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /usr/local/lib/python3.11/dist-packages (from torch->timm) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /usr/local/lib/python3.11/dist-packages (from torch->timm) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch->timm) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /usr/local/lib/python3.11/dist-packages (from torch->timm) (12.1.105)
Requirement already satisfied: triton==3.1.0 in /usr/local/lib/python3.11/dist-packages (from torch->timm) (3.1.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch->timm) (1.13.1)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.11/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch->timm) (12.6.85)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch->timm) (1.3.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from torchvision->timm) (1.26.4)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.11/dist-packages (from torchvision->timm) (11.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch->timm) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface_hub->timm) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface_hub->timm) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface_hub->timm) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface_hub->timm) (2024.12.14)

In [ ]:
from fastai.vision.all import *

In [ ]:
from fastai.tabular.all import *
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
PALM_URL = "https://prod-dcd-datasets-cache-zipfiles.s3.eu-west-1.amazonaws.com/ccr8cm22vz-1.zip"
path = untar_data(PALM_URL)

In [ ]:
!pip install rarfile av

Collecting rarfile
  Downloading rarfile-4.2-py3-none-any.whl.metadata (4.4 kB)
Collecting av
  Downloading av-14.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.5 kB)
Downloading rarfile-4.2-py3-none-any.whl (29 kB)
Downloading av-14.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (33.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.8/33.8 MB 66.2 MB/s eta 0:00:00
Installing collected packages: rarfile, av
Successfully installed av-14.0.1 rarfile-4.2

In [ ]:
!pip install fastai2

Collecting fastai2
  Downloading fastai2-0.0.30-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: pip in /usr/local/lib/python3.11/dist-packages (from fastai2) (24.1.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from fastai2) (24.2)
Requirement already satisfied: fastcore>=0.1.34 in /usr/local/lib/python3.11/dist-packages (from fastai2) (1.7.28)
Requirement already satisfied: torchvision>=0.7 in /usr/local/lib/python3.11/dist-packages (from fastai2) (0.20.1+cu121)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from fastai2) (3.10.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from fastai2) (2.2.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from fastai2) (2.32.3)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.11/dist-packages (from fastai2) (6.0.2)
Requirement already satisfied: fastprogress>=0.2.4 in /usr/local/lib/python3.11/dist-packages (from fastai2) (1.0.3)
Requirement already satisfied: pillow in /usr/local/lib/python3.11/dist-packages (from fastai2) (11.1.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from fastai2) (1.6.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from fastai2) (1.13.1)
Requirement already satisfied: spacy in /usr/local/lib/python3.11/dist-packages (from fastai2) (3.7.5)
Requirement already satisfied: torch>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from fastai2) (2.5.1+cu121)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch>=1.6.0->fastai2) (3.16.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.6.0->fastai2) (4.12.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.6.0->fastai2) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.6.0->fastai2) (3.1.5)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch>=1.6.0->fastai2) (2024.10.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /usr/local/lib/python3.11/dist-packages (from torch>=1.6.0->fastai2) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /usr/local/lib/python3.11/dist-packages (from torch>=1.6.0->fastai2) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /usr/local/lib/python3.11/dist-packages (from torch>=1.6.0->fastai2) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch>=1.6.0->fastai2) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.6.0->fastai2) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /usr/local/lib/python3.11/dist-packages (from torch>=1.6.0->fastai2) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /usr/local/lib/python3.11/dist-packages (from torch>=1.6.0->fastai2) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /usr/local/lib/python3.11/dist-packages (from torch>=1.6.0->fastai2) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /usr/local/lib/python3.11/dist-packages (from torch>=1.6.0->fastai2) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.6.0->fastai2) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /usr/local/lib/python3.11/dist-packages (from torch>=1.6.0->fastai2) (12.1.105)
Requirement already satisfied: triton==3.1.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.6.0->fastai2) (3.1.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.6.0->fastai2) (1.13.1)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.11/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.6.0->fastai2) (12.6.85)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.6.0->fastai2) (1.3.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from torchvision>=0.7->fastai2) (1.26.4)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->fastai2) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->fastai2) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->fastai2) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->fastai2) (1.4.8)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->fastai2) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib->fastai2) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->fastai2) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->fastai2) (2024.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->fastai2) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->fastai2) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->fastai2) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->fastai2) (2024.12.14)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->fastai2) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->fastai2) (3.5.0)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.11/dist-packages (from spacy->fastai2) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from spacy->fastai2) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.11/dist-packages (from spacy->fastai2) (1.0.11)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.11/dist-packages (from spacy->fastai2) (2.0.10)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.11/dist-packages (from spacy->fastai2) (3.0.9)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in /usr/local/lib/python3.11/dist-packages (from spacy->fastai2) (8.2.5)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.11/dist-packages (from spacy->fastai2) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.11/dist-packages (from spacy->fastai2) (2.5.0)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.11/dist-packages (from spacy->fastai2) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.11/dist-packages (from spacy->fastai2) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from spacy->fastai2) (0.15.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.11/dist-packages (from spacy->fastai2) (4.67.1)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.11/dist-packages (from spacy->fastai2) (2.10.5)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from spacy->fastai2) (75.1.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.11/dist-packages (from spacy->fastai2) (3.5.0)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.11/dist-packages (from langcodes<4.0.0,>=3.2.0->spacy->fastai2) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy->fastai2) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy->fastai2) (2.27.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib->fastai2) (1.17.0)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.11/dist-packages (from thinc<8.3.0,>=8.2.2->spacy->fastai2) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.11/dist-packages (from thinc<8.3.0,>=8.2.2->spacy->fastai2) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy->fastai2) (8.1.8)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy->fastai2) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy->fastai2) (13.9.4)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from weasel<0.5.0,>=0.1.0->spacy->fastai2) (0.20.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.11/dist-packages (from weasel<0.5.0,>=0.1.0->spacy->fastai2) (7.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.6.0->fastai2) (3.0.2)
Requirement already satisfied: marisa-trie>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy->fastai2) (1.2.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy->fastai2) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy->fastai2) (2.18.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy->fastai2) (1.17.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy->fastai2) (0.1.2)
Downloading fastai2-0.0.30-py3-none-any.whl (179 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.4/179.4 kB 3.4 MB/s eta 0:00:00
Installing collected packages: fastai2
Successfully installed fastai2-0.0.30

In [ ]:
from fastai.data import *

In [ ]:
!unrar x /root/.fastai/data/ccr8cm22vz-1/Palm.rar

UNRAR 6.11 beta 1 freeware      Copyright (c) 1993-2022 Alexander Roshal


Extracting from /root/.fastai/data/ccr8cm22vz-1/Palm.rar

Creating    Palm                                                      OK
Extracting  Palm/Anemic-260 (10).png                                       0%  OK
Extracting  Palm/Anemic-260 (11).png                                       0%  OK
Extracting  Palm/Anemic-260 (12).png                                       0%  OK
Extracting  Palm/Anemic-260 (2).png                                        0%  OK
Extracting  Palm/Anemic-260 (3).png                                        0%  OK
Extracting  Palm/Anemic-260 (4).png                                        0%  OK
Extracting  Palm/Anemic-260 (5).png                                        0%  OK
Extracting  Palm/Anemic-260 (6).png                                        0%  OK
Extracting  Palm/Anemic-260 (7).png                                        0%  OK
Extracting  Palm/Anemic-260 (8).png                                        0%  OK
Extracting  Palm/Anemic-260 (9).png                                        0%  OK
Extracting  Palm/Anemic-262 (10).png                                       0%  OK
Extracting  Palm/Anemic-262 (11).png                                       0%  OK
Extracting  Palm/Anemic-262 (12).png                                       0%  OK
Extracting  Palm/Anemic-262 (2).png                                        0%  OK
Extracting  Palm/Anemic-262 (3).png                                        0%  OK
Extracting  Palm/Anemic-262 (4).png                                        0%  OK
Extracting  Palm/Anemic-262 (5).png                                        0%  OK
Extracting  Palm/Anemic-262 (6).png                                        0%  OK
Extracting  Palm/Anemic-262 (7).png                                        0%  OK
Extracting  Palm/Anemic-262 (8).png                                        0%  OK
Extracting  Palm/Anemic-262 (9).png                                        0%  OK
Extracting  Palm/Anemic-262.png                                            0%  OK
Extracting  Palm/Anemic-264 (10).png                                       0%  OK
Extracting  Palm/Anemic-264 (11).png                                       0%  OK
Extracting  Palm/Anemic-264 (12).png                                       0%  OK
Extracting  Palm/Anemic-264 (2).png                                        0%  OK
Extracting  Palm/Anemic-264 (3).png                                        0%  OK
Extracting  Palm/Anemic-264 (4).png                                        0%  OK
Extracting  Palm/Anemic-264 (5).png                                        0%  OK
Extracting  Palm/Anemic-264 (6).png                                        0%  OK
Extracting  Palm/Anemic-264 (7).png                                        0%  OK
Extracting  Palm/Anemic-264 (8).png                                        0%  OK
Extracting  Palm/Anemic-264 (9).png                                        0%  OK
Extracting  Palm/Anemic-264.png                                            0%  OK
Extracting  Palm/Anemic-265 (10).png                                       0%  OK
Extracting  Palm/Anemic-265 (11).png                                       0%  OK
Extracting  Palm/Anemic-265 (12).png                                       0%  OK
Extracting  Palm/Anemic-265 (2).png                                        0%  OK
Extracting  Palm/Anemic-265 (3).png                                        0%  OK
Extracting  Palm/Anemic-265 (4).png                                        0%  OK
Extracting  Palm/Anemic-265 (5).png                                        0%  OK
Extracting  Palm/Anemic-265 (6).png                                        0%  OK
Extracting  Palm/Anemic-265 (7) - Copy.png                                 0%  OK
Extracting  Palm/Anemic-265 (7).png                                        0%  OK
Extracting  Palm/Anemic-265 (8).png                                        0%  OK
Extracting  Palm/Anemic-265 (9).png                                        0%  OK
Extracting  Palm/Anemic-265.png                                            0%  OK
Extracting  Palm/Anemic-266 (10).png                                       0%  OK
Extracting  Palm/Anemic-266 (11).png                                       0%  OK
Extracting  Palm/Anemic-266 (12).png                                       0%  OK
Extracting  Palm/Anemic-266 (2).png                                        0%  OK
Extracting  Palm/Anemic-266 (3).png                                        0%  OK
Extracting  Palm/Anemic-266 (4).png                                        0%  OK
Extracting  Palm/Anemic-266 (5).png                                        0%  OK
Extracting  Palm/Anemic-266 (6).png                                        0%  OK
Extracting  Palm/Anemic-266 (7).png                                        0%  OK
Extracting  Palm/Anemic-266 (8).png                                        0%  OK
Extracting  Palm/Anemic-266 (9).png                                        0%  OK
Extracting  Palm/Anemic-266.png                                            0%  OK
Extracting  Palm/Anemic-267 (10).png                                       0%  OK
Extracting  Palm/Anemic-267 (11).png                                       0%  OK
Extracting  Palm/Anemic-267 (12).png                                       0%  OK
Extracting  Palm/Anemic-267 (2).png                                        0%  OK
Extracting  Palm/Anemic-267 (3).png                                        0%  OK
Extracting  Palm/Anemic-267 (4).png                                        0%  OK
Extracting  Palm/Anemic-267 (5).png                                        0%  OK
Extracting  Palm/Anemic-267 (6).png                                        0%  OK
Extracting  Palm/Anemic-267 (7).png                                        0%  OK
Extracting  Palm/Anemic-267 (8).png                                        0%  OK
Extracting  Palm/Anemic-267 (9).png                                        0%  OK
Extracting  Palm/Anemic-267.png                                            0%  OK
Extracting  Palm/Anemic-268 (10).png                                       0%  OK
Extracting  Palm/Anemic-268 (11).png                                       0%  OK
Extracting  Palm/Anemic-268 (12).png                                       0%  OK
Extracting  Palm/Anemic-268 (2).png                                        0%  OK
Extracting  Palm/Anemic-268 (3).png                                        0%  OK
Extracting  Palm/Anemic-268 (4).png                                        0%  OK
Extracting  Palm/Anemic-268 (5).png                                        0%  OK
Extracting  Palm/Anemic-268 (6).png                                        0%  OK
Extracting  Palm/Anemic-268 (7).png                                        0%  OK
Extracting  Palm/Anemic-268 (8).png                                        0%  OK
Extracting  Palm/Anemic-268 (9).png                                        0%  OK
Extracting  Palm/Anemic-268.png                                            1%  OK
Extracting  Palm/Anemic-268FV (10).png                                     1%  OK
Extracting  Palm/Anemic-268FV (11).png                                     1%  OK
Extracting  Palm/Anemic-268FV (12).png                                     1%  OK
Extracting  Palm/Anemic-268FV (2).png                                      1%  OK
Extracting  Palm/Anemic-268FV (3).png                                      1%  OK
Extracting  Palm/Anemic-268FV (4).png                                      1%  OK
Extracting  Palm/Anemic-268FV (5).png                                      1%  OK
Extracting  Palm/Anemic-268FV (6).png                                      1%  OK
Extracting  Palm/Anemic-268FV (7).png                                      1%  OK
Extracting  Palm/Anemic-268FV (8).png                                      1%  OK
Extracting  Palm/Anemic-268FV (9).png                                      1%  OK
Extracting  Palm/Anemic-268FV.png                                          1%  OK
Extracting  Palm/Anemic-268RA (10).png                                     1%  OK
Extracting  Palm/Anemic-268RA (11).png                                     1%  OK
Extracting  Palm/Anemic-268RA (12).png                                     1%  OK
Extracting  Palm/Anemic-268RA (2).png                                      1%  OK
Extracting  Palm/Anemic-268RA (3).png                                      1%  OK
Extracting  Palm/Anemic-268RA (4).png                                      1%  OK
Extracting  Palm/Anemic-268RA (5).png                                      1%  OK
Extracting  Palm/Anemic-268RA (6).png                                      1%  OK
Extracting  Palm/Anemic-268RA (7).png                                      1%  OK
Extracting  Palm/Anemic-268RA (8).png                                      1%  OK
Extracting  Palm/Anemic-268RA (9).png                                      1%  OK
Extracting  Palm/Anemic-268RA.png                                          1%  OK
Extracting  Palm/Anemic-269 (10).png                                       1%  OK
Extracting  Palm/Anemic-269 (11).png                                       1%  OK
Extracting  Palm/Anemic-269 (12).png                                       1%  OK
Extracting  Palm/Anemic-269 (2).png                                        1%  OK
Extracting  Palm/Anemic-269 (3).png                                        1%  OK
Extracting  Palm/Anemic-269 (4).png                                        1%  OK
Extracting  Palm/Anemic-269 (5).png                                        1%  OK
Extracting  Palm/Anemic-269 (6).png                                        1%  OK
Extracting  Palm/Anemic-269 (7).png                                        1%  OK
Extracting  Palm/Anemic-269 (8).png                                        1%  OK
Extracting  Palm/Anemic-269 (9).png                                        1%  OK
Extracting  Palm/Anemic-269.png                                            1%  OK
Extracting  Palm/Anemic-271 (10).png                                       1%  OK
Extracting  Palm/Anemic-271 (11).png                                       1%  OK
Extracting  Palm/Anemic-271 (12).png                                       1%  OK
Extracting  Palm/Anemic-271 (2).png                                        1%  OK
Extracting  Palm/Anemic-271 (3).png                                        1%  OK
Extracting  Palm/Anemic-271 (4).png                                        1%  OK
Extracting  Palm/Anemic-271 (5).png                                        1%  OK
Extracting  Palm/Anemic-271 (6).png                                        1%  OK
Extracting  Palm/Anemic-271 (7).png                                        1%  OK
Extracting  Palm/Anemic-271 (8).png                                        1%  OK
Extracting  Palm/Anemic-271 (9).png                                        1%  OK
Extracting  Palm/Anemic-271.png                                            1%  OK
Extracting  Palm/Anemic-272 (10).png                                       2%  OK
Extracting  Palm/Anemic-272 (11).png                                       2%  OK
Extracting  Palm/Anemic-272 (12).png                                       2%  OK
Extracting  Palm/Anemic-272 (2).png                                        2%  OK
Extracting  Palm/Anemic-272 (3).png                                        2%  OK
Extracting  Palm/Anemic-272 (4).png                                        2%  OK
Extracting  Palm/Anemic-272 (5).png                                        2%  OK
Extracting  Palm/Anemic-272 (6).png                                        2%  OK
Extracting  Palm/Anemic-272 (7).png                                        2%  OK
Extracting  Palm/Anemic-272 (8).png                                        2%  OK
Extracting  Palm/Anemic-272 (9).png                                        2%  OK
Extracting  Palm/Anemic-272.png                                            2%  OK
Extracting  Palm/Anemic-Pa-001 (2).png                                     2%  OK
Extracting  Palm/Anemic-Pa-001 (3).png                                     2%  OK
Extracting  Palm/Anemic-Pa-001 (4).png                                     2%  OK
Extracting  Palm/Anemic-Pa-001 (5).png                                     2%  OK
Extracting  Palm/Anemic-Pa-001 (6).png                                     2%  OK
Extracting  Palm/Anemic-Pa-001.png                                         2%  OK
Extracting  Palm/Anemic-Pa-002 (2).png                                     2%  OK
Extracting  Palm/Anemic-Pa-002 (3).png                                     2%  OK
Extracting  Palm/Anemic-Pa-002 (4).png                                     2%  OK
Extracting  Palm/Anemic-Pa-002 (5).png                                     2%  OK
Extracting  Palm/Anemic-Pa-002 (6).png                                     2%  OK
Extracting  Palm/Anemic-Pa-002.png                                         2%  OK
Extracting  Palm/Anemic-Pa-003 (2).png                                     2%  OK
Extracting  Palm/Anemic-Pa-003 (3).png                                     3%  OK
Extracting  Palm/Anemic-Pa-003 (4).png                                     3%  OK
Extracting  Palm/Anemic-Pa-003 (5).png                                     3%  OK
Extracting  Palm/Anemic-Pa-003 (6).png                                     3%  OK
Extracting  Palm/Anemic-Pa-003.png                                         3%  OK
Extracting  Palm/Anemic-Pa-004 (2).png                                     3%  OK
Extracting  Palm/Anemic-Pa-004 (3).png                                     3%  OK
Extracting  Palm/Anemic-Pa-004 (4).png                                     3%  OK
Extracting  Palm/Anemic-Pa-004 (5).png                                     3%  OK
Extracting  Palm/Anemic-Pa-004 (6).png                                     3%  OK
Extracting  Palm/Anemic-Pa-004.png                                         3%  OK
Extracting  Palm/Anemic-Pa-005 (2).png                                     3%  OK
Extracting  Palm/Anemic-Pa-005 (3).png                                     3%  OK
Extracting  Palm/Anemic-Pa-005 (4).png                                     3%  OK
Extracting  Palm/Anemic-Pa-005 (5).png                                     3%  OK
Extracting  Palm/Anemic-Pa-005 (6).png                                     3%  OK
Extracting  Palm/Anemic-Pa-005.png                                         3%  OK
Extracting  Palm/Anemic-Pa-006 (2).png                                     3%  OK
Extracting  Palm/Anemic-Pa-006 (3).png                                     3%  OK
Extracting  Palm/Anemic-Pa-006 (4).png                                     3%  OK
Extracting  Palm/Anemic-Pa-006 (5).png                                     3%  OK
Extracting  Palm/Anemic-Pa-006 (6).png                                     3%  OK
Extracting  Palm/Anemic-Pa-006.png                                         3%  OK
Extracting  Palm/Anemic-Pa-007 (2).png                                     3%  OK
Extracting  Palm/Anemic-Pa-007 (3).png                                     3%  OK
Extracting  Palm/Anemic-Pa-007 (4).png                                     3%  OK
Extracting  Palm/Anemic-Pa-007 (5).png                                     3%  OK
Extracting  Palm/Anemic-Pa-007 (6).png                                     3%  OK
Extracting  Palm/Anemic-Pa-007.png                                         3%  OK
Extracting  Palm/Anemic-Pa-008 (2).png                                     3%  OK
Extracting  Palm/Anemic-Pa-008 (3).png                                     3%  OK
Extracting  Palm/Anemic-Pa-008 (4).png                                     3%  OK
Extracting  Palm/Anemic-Pa-008 (5).png                                     3%  OK
Extracting  Palm/Anemic-Pa-008 (6).png                                     3%  OK
Extracting  Palm/Anemic-Pa-008.png                                         3%  OK
Extracting  Palm/Anemic-Pa-009 (2).png                                     3%  OK
Extracting  Palm/Anemic-Pa-009 (3).png                                     3%  OK
Extracting  Palm/Anemic-Pa-009 (4).png                                     3%  OK
Extracting  Palm/Anemic-Pa-009 (5).png                                     3%  OK
Extracting  Palm/Anemic-Pa-009 (6).png                                     3%  OK
Extracting  Palm/Anemic-Pa-009.png                                         3%  OK
Extracting  Palm/Anemic-Pa-010 (2).png                                     3%  OK
Extracting  Palm/Anemic-Pa-010 (3).png                                     3%  OK
Extracting  Palm/Anemic-Pa-010 (4).png                                     3%  OK
Extracting  Palm/Anemic-Pa-010 (5).png                                     3%  OK
Extracting  Palm/Anemic-Pa-010 (6).png                                     3%  OK
Extracting  Palm/Anemic-Pa-010.png                                         3%  OK
Extracting  Palm/Anemic-Pa-011 (2).png                                     3%  OK
Extracting  Palm/Anemic-Pa-011 (3).png                                     3%  OK
Extracting  Palm/Anemic-Pa-011 (4).png                                     3%  OK
Extracting  Palm/Anemic-Pa-011 (5).png                                     3%  OK
Extracting  Palm/Anemic-Pa-011 (6).png                                     3%  OK
Extracting  Palm/Anemic-Pa-011.png                                         3%  OK
Extracting  Palm/Anemic-Pa-012 (2).png                                     3%  OK
Extracting  Palm/Anemic-Pa-012 (3).png                                     3%  OK
Extracting  Palm/Anemic-Pa-012 (4).png                                     4%  OK
Extracting  Palm/Anemic-Pa-012 (5).png                                     4%  OK
Extracting  Palm/Anemic-Pa-012 (6).png                                     4%  OK
Extracting  Palm/Anemic-Pa-012.png                                         4%  OK
Extracting  Palm/Anemic-Pa-013 (2).png                                     4%  OK

In [ ]:
PALM_ROOT = "/content/Palm"
files = get_image_files(PALM_ROOT)
files[0], files[10]

(Path('/content/Palm/Non-AnemicP-118 (2).png'),
 Path('/content/Palm/AnemicP-224 (6).png'))

In [ ]:
path = Path(PALM_ROOT)
path

Path('/content/Palm')

In [ ]:
def is_anemic(f): return "non-anemic" not in f.lower()

In [ ]:
dls = ImageDataLoaders.from_name_func(path, files, is_anemic, item_tfms=Resize(128))

In [ ]:
cbc_data_path = '/content/drive/MyDrive/anemia.csv'
cbc_data = pd.read_csv(cbc_data_path)

In [ ]:
cat_names = ['Gender']
cont_names = ['Hemoglobin', 'MCH', 'MCHC', 'MCV']
y_names = 'Result'

procs = [Categorify, FillMissing, Normalize]

dls_tab = TabularDataLoaders.from_df(
    cbc_data,
    procs=procs,
    cat_names=cat_names,
    cont_names=cont_names,
    y_names=y_names,
    y_block=CategoryBlock(),
    splits=RandomSplitter()(range_of(cbc_data))
)

In [ ]:
class MultiModalModel(nn.Module):
    def __init__(self, image_model, tabular_input_size, num_classes):
        super().__init__()
        self.image_model = image_model
        self.tabular_model = nn.Sequential(
            nn.Linear(tabular_input_size, 128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.ReLU()
        )
        self.fusion_layer = nn.Linear(image_model.num_features + 64, 256)
        self.classifier = nn.Linear(256, num_classes)

    def forward(self, image, tabular):
        img_features = self.image_model(image)
        tabular_features = self.tabular_model(tabular)
        combined = torch.cat([img_features, tabular_features], dim=1)
        fused = self.fusion_layer(combined)
        return self.classifier(fused)

In [ ]:
from timm import list_models
print(list_models('*convnext*'))

['convnext_atto', 'convnext_atto_ols', 'convnext_atto_rms', 'convnext_base', 'convnext_femto', 'convnext_femto_ols', 'convnext_large', 'convnext_large_mlp', 'convnext_nano', 'convnext_nano_ols', 'convnext_pico', 'convnext_pico_ols', 'convnext_small', 'convnext_tiny', 'convnext_tiny_hnf', 'convnext_xlarge', 'convnext_xxlarge', 'convnext_zepto_rms', 'convnext_zepto_rms_ols', 'convnextv2_atto', 'convnextv2_base', 'convnextv2_femto', 'convnextv2_huge', 'convnextv2_large', 'convnextv2_nano', 'convnextv2_pico', 'convnextv2_small', 'convnextv2_tiny', 'test_convnext', 'test_convnext2', 'test_convnext3']

In [ ]:
# Assuming 'dls' from your earlier code refers to the ImageDataLoaders object,
# you can simply assign it to dls_img:
dls_img = dls

In [ ]:
# Step 5: Train Image Model
learn_img = vision_learner(dls_img, 'convnext_tiny', metrics=error_rate, pretrained=True)
learn_img.fine_tune(10)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

model.safetensors:   0%|          | 0.00/114M [00:00<?, ?B/s]

In [ ]:
# Step 6: Train Tabular Model
learn_tab = tabular_learner(dls_tab, metrics=accuracy)
learn_tab.fit_one_cycle(10, lr_max=1e-3)

In [ ]:
# Step 6: Extract Independent Embeddings
# Extract image embeddings
image_dl = dls_img.test_dl(files)
image_preds, _ = learn_img.get_preds(dl=image_dl)
image_embeddings = image_preds.numpy()
# Extract CBC embeddings
cbc_preds, _ = learn_tab.get_preds(dl=dls_tab.train)
cbc_embeddings = cbc_preds.numpy()

In [ ]:
# Step 7: Handle Independent Datasets with Padding
image_dim = image_embeddings.shape[1]
cbc_dim = cbc_embeddings.shape[1]

# Match dimensions by padding smaller embedding
if len(image_embeddings) > len(cbc_embeddings):
    cbc_embeddings = np.pad(cbc_embeddings, ((0, len(image_embeddings) - len(cbc_embeddings)), (0, 0)))
elif len(image_embeddings) < len(cbc_embeddings):
    image_embeddings = np.pad(image_embeddings, ((0, len(cbc_embeddings) - len(image_embeddings)), (0, 0)))

# Combine features
combined_features = np.hstack([image_embeddings, cbc_embeddings])

# Labels (Ensure correct alignment; here using CBC labels as a placeholder)
labels = cbc_data['Result'].values
if len(labels) < len(combined_features):
    labels = np.pad(labels, (0, len(combined_features) - len(labels)))

In [ ]:
# Step 8: Train Fusion Classifier
X_train, X_test, y_train, y_test = train_test_split(combined_features, labels, test_size=0.2, random_state=42)

clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train, y_train)
# Evaluate
y_pred = clf.predict(X_test)
print(f"Fusion Model Accuracy: {accuracy_score(y_test, y_pred)}")

Fusion Model Accuracy: 0.8098591549295775

In [ ]:
# Step 9: Conflict Handling Logic
# Example: Use probabilities from RandomForest to simulate confidence thresholds
image_prob = 0.8  # Placeholder for image-driven anemia probability
cbc_prob = 0.4    # Placeholder for CBC-driven anemia probability

if image_prob >= 0.7 and cbc_prob < 0.5:
    final_result = "Anemic (Image-driven)"
elif cbc_prob >= 0.7 and image_prob < 0.5:
    final_result = "Non-anemic (CBC-driven)"
else:
    final_result = "Uncertain (Conflicting inputs)"

print(f"Final Decision: {final_result}")

Final Decision: Anemic (Image-driven)

In [ ]:
# Step 10: Save Models
learn_img.export('/content/drive/MyDrive/image_model.pkl')
learn_tab.export('/content/drive/MyDrive/tabular_model.pkl')
import joblib
joblib.dump(clf, '/content/drive/MyDrive/fusion_model.pkl')

['/content/drive/MyDrive/fusion_model.pkl']

In [ ]:
# Save Fusion Model as PTH
fusion_model_path = '/content/drive/MyDrive/fusion_model.pth'
combined_features_tensor = torch.tensor(combined_features)
torch.save({'model_state_dict': clf, 'features': combined_features_tensor}, fusion_model_path)
print(f"Fusion model saved to {fusion_model_path}")

Fusion model saved to /content/drive/MyDrive/fusion_model.pth